version: '3.2'

services:
  postgres-database:
    container_name: kipaji-db
    ports:
      - "5434:5432"
    build: 
      context: .
      dockerfile: Dockerfile-postgres
    image: kipaji/postgres:1.0.0
    shm_size: 1g
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    volumes:
      - ./files/db:/tmp/db
      - postdb-data:/var/lib/postgresql/data
    networks: 
      - backend
  nginx:
    container_name: kipaji-nginx
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx/kipaji-nginx:1.0.0
    ports:
      - "5000:3000"
    restart: always
    networks: 
      - backend
pgadmin4:
    container_name: pgadmin4
    restart: always
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - pga4:/var/lib/pgadmin
    ports:
      - 5050:5050
    networks:
      - pgnetwork
  api:
    container_name: kipaji-api
    image: kipaji/api
    build: .
    restart: always
    command: npm run start:dev
    volumes:
      - type: bind
        source: ./src
        target: /home/app/src
      - type: bind
        source: ./files
        target: /home/app/files
    networks: 
      - backend
networks:
  backend:
    driver: "bridge"
volumes:
  postdb-data:
    driver: local